// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1SeunTz0LLhU3_th4mZpafLe6CgLUqc',
    appId: '1:171155844004:web:d6704f37f8e5737e3e2f31',
    messagingSenderId: '171155844004',
    projectId: 'muslimin-app-bd',
    authDomain: 'muslimin-app-bd.firebaseapp.com',
    storageBucket: 'muslimin-app-bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslIrMD6zubAHEUAqC_8Ia4cvxd2evB6Y',
    appId: '1:171155844004:android:56d1ee3a4498a0d93e2f31',
    messagingSenderId: '171155844004',
    projectId: 'muslimin-app-bd',
    storageBucket: 'muslimin-app-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAubnLinSNbI7SZDX_BhPgjDrErcfwt0fs',
    appId: '1:171155844004:ios:d412649afcd6cf683e2f31',
    messagingSenderId: '171155844004',
    projectId: 'muslimin-app-bd',
    storageBucket: 'muslimin-app-bd.firebasestorage.app',
    iosBundleId: 'com.muslimin.muslimin',
  );
}
